### ISSUE TITLE
The Logarithm description is wrong

### ISSUE THREAD

**Issue by fomlhaut** [sergeyqz/jcheatsheet#2]
In [data.tsv, line 54](https://github.com/sergeyqz/jcheatsheet/blob/6338103504ab28c52d18b8035d5a4ab328084284/data.tsv#L54), where it says:
` logarithm of ``LN`` to the base ``RN`` `
it should say:
` logarithm of ``RN`` to the base ``LN`` `

Thus, in [index.html](https://github.com/sergeyqz/jcheatsheet/blob/6338103504ab28c52d18b8035d5a4ab328084284/index.html#L426) `A` and `B` must also be swapped.

**Comment by sergeyqz** [comment]
Thanks a lot for the fix!
